# Generated by Django 4.0.4 on 2022-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvs',
            name='activated',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='csvs',
            name='file_name',
            field=models.FileField(upload_to='csvs'),
        ),
    ]
